/*
 * DO NOT EDIT THIS FILE. Generated by checkmk.
 * Edit the original source file "game-test.check" instead.
 */

#include <check.h>

#line 1 "game-test.check"
#include "game.h"

START_TEST(game)
{
#line 4
     short* board[4];
     int i;
     for(i = 0; i < 4; i++)
     {
         short row[] = {0, 0, 0, 0};
         board[i] = &row;
     }
    fail_unless(is_equal(new_board(), board));
}
END_TEST

int main(void)
{
    Suite *s1 = suite_create("Core");
    TCase *tc1_1 = tcase_create("Core");
    SRunner *sr = srunner_create(s1);
    int nf;

    suite_add_tcase(s1, tc1_1);
    tcase_add_test(tc1_1, game);

    srunner_run_all(sr, CK_ENV);
    nf = srunner_ntests_failed(sr);
    srunner_free(sr);

    return nf == 0 ? 0 : 1;
}
