void new_game_board(int (*board)[4]);
void add_random_tile(int tile, int (*board)[4]);
void add_random_tile_start(int (*board)[4]);
void fill_zero(int row[4], int start);
void copy_row(int source[4], int destination[4]);
void move_row_left(int row[4]);
void move_board_left(int (*board)[4]);
void print_row(int row[4]);
void print_board(int (*board)[4]);
int is_equal_row(int row1[4], int row2[4]);
int is_equal_board(int (*board1)[4], int (*board2)[4]);
int frequence(int (*board)[4], int number);
