void new_game_board(int (*board)[4]);
void add_random_tile(int tile, int (*board)[4]);
void add_random_tile_start(int (*board)[4]);
void fill_zero(int row[4], int start, char direction);
void copy_row(int source[4], int destination[4]);
void copy_board(int (*source)[4], int (*destination)[4]);
void reverse_row(int row[], int size);
void move_row(int row[4], char direction);
void transpose(int (*board)[4]);
void move_board(int (*board)[4], char direction);
void print_row(int row[4]);
void print_board(int (*board)[4]);
int is_equal_row(int row1[4], int row2[4]);
int is_equal_board(int (*board1)[4], int (*board2)[4]);
int frequence(int (*board)[4], int number);
void play();
int is_lost(int (*board)[4]);
